version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"  # O "5433:5432" si prefieres el puerto 5433
    environment:
      POSTGRES_DB: vehicle_management
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d vehicle_management"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: